FROM node:16.17-alpine as dependencies

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

FROM node:16.17-alpine as builder

WORKDIR /app

ARG VITE_BACKEND_ENDPOINT
ENV VITE_BACKEND_ENDPOINT=$VITE_BACKEND_ENDPOINT
ARG VITE_BACKEND_WEBSOCKET
ENV VITE_BACKEND_WEBSOCKET=$VITE_BACKEND_WEBSOCKET

COPY . .
COPY --from=dependencies /app/node_modules ./node_modules
RUN yarn build

FROM nginx:alpine

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY --from=builder /app/dist .

CMD [ "nginx", "-g", "daemon off;" ]
