FROM node:16.17-alpine as dependencies

WORKDIR /app

COPY package.json pnpm-lock.lock ./
RUN pnpm install --frozen-lockfile

FROM node:16.17-alpine as builder

WORKDIR /app

COPY . .
COPY --from=dependencies /app/node_modules ./node_modules
RUN pnpm build

FROM node:16.17-alpine

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

CMD [ "pnpm", "start" ]
